name: Build

on:
  push:
  workflow_dispatch: 

jobs:
  build:
    name: Core
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup multi arch prerequisites
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate tags for core
        uses: docker/metadata-action@v5.4.0
        id: core-meta
        with:
          bake-target: core
          images: |
            ghcr.io/${{ github.repository_owner }}/core
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
    
      - name: Generate tags for redis
        uses: docker/metadata-action@v5.4.0
        id: redis-meta
        with:
          bake-target: redis
          images: |
            ghcr.io/${{ github.repository_owner }}/redis
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Generate tags for restic
        uses: docker/metadata-action@v5.4.0
        id: restic-meta
        with:
          bake-target: restic
          images: |
            ghcr.io/${{ github.repository_owner }}/restic
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Generate tags for rsync
        uses: docker/metadata-action@v5.4.0
        id: rsync-meta
        with:
          bake-target: rsync
          images: |
            ghcr.io/${{ github.repository_owner }}/rsync
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build
        uses: docker/bake-action@v5
        with:
          targets: default
          push: true
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
          files: |
            docker-bake.hcl
            ${{ steps.core-meta.outputs.bake-file }}
            ${{ steps.redis-meta.outputs.bake-file }}
            ${{ steps.restic-meta.outputs.bake-file }}
            ${{ steps.rsync-meta.outputs.bake-file }}

